### ISSUE TITLE
Исправить автодополнение

### ISSUE THREAD

**Issue by ensirius** [Ensemplix/Bundle#13]
```java
[20:32:15 ERROR]: [Bundle] Unhandled exception occured in onPacketReceiving(PacketEvent) for Bundle
java.lang.ArrayIndexOutOfBoundsException: 1
        at ru.ensemplix.command.dispatcher.SimpleCommandDispatcher.complete(SimpleCommandDispatcher.kt:200) ~[CraftBundle-4.0-SNAPSHOT.jar:?]
        at ru.ensemplix.bukkit.listener.packet.CraftBundleTabCompletePacketListener.onPacketReceiving(CraftBundleTabCompletePacketListener.java:38) ~[CraftBundle-4.0-SNAPSHOT.jar:?]
```

**Comment by ensirius** [comment]
На данный момент как будто бы исправлено
